"""
YOLO Training Script for LineMOD Dataset

Fine-tune yolo on LineMOD dataset using custom dataset loader.
No data duplication - reads directly from Linemod_preprocessed structure.
"""

import argparse
import sys
from pathlib import Path
import tempfile
import shutil

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from config import Config
from models.yolo_detector import YOLODetector
from dataset.linemod_yolo_dataset import create_yolo_dataloaders


def create_temp_data_yaml(dataset_root, temp_dir):
    """
    Create a temporary data.yaml file for YOLO training.
    This is needed for Ultralytics API compatibility.
    
    Args:
        dataset_root: Path to dataset root
        temp_dir: Temporary directory to store yaml file
    
    Returns:
        Path to data.yaml file
    """
    yaml_content = f"""# LineMOD Dataset Configuration for YOLO
# Auto-generated by train_yolo.py

path: {str(dataset_root)}
train: data  # Will use custom dataset loader
val: data    # Will use custom dataset loader

# Classes (13 LineMOD objects)
names:
  0: ape
  1: benchvise
  2: camera
  3: can
  4: cat
  5: driller
  6: duck
  7: eggbox
  8: glue
  9: holepuncher
  10: iron
  11: lamp
  12: phone
"""
    
    yaml_path = Path(temp_dir) / 'linemod_temp.yaml'
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    
    return yaml_path


def parse_args():
    parser = argparse.ArgumentParser(description='Train yolo on LineMOD Dataset')
    
    # Data parameters
    parser.add_argument('--data_yaml', type=str, default=None,
                       help='Path to data.yaml (if not provided, will use symlinks dataset)')
    parser.add_argument('--data_dir', type=str, default=str(Config.DATA_ROOT),
                       help='Path to Linemod_preprocessed root')
    parser.add_argument('--batch_size', type=int, default=Config.YOLO_BATCH_SIZE,
                       help='Batch size')
    parser.add_argument('--num_workers', type=int, default=Config.NUM_WORKERS,
                       help='Number of data loading workers (adaptive: 4 for MPS, 2 for CPU/Colab, 8 for CUDA)')
    
    # Model parameters
    parser.add_argument('--model', type=str, default=Config.YOLO_MODEL,
                       help='YOLO model variant (yolo11n, yolo11s, yolo11m, etc.)')
    parser.add_argument('--pretrained', action='store_true', default=Config.PRETRAINED,
                       help='Use pretrained COCO weights')
    
    # Training parameters
    parser.add_argument('--epochs', type=int, default=Config.YOLO_EPOCHS,
                       help='Number of training epochs')
    parser.add_argument('--lr', type=float, default=Config.YOLO_LR,
                       help='Initial learning rate')
    parser.add_argument('--imgsz', type=int, default=Config.YOLO_IMGSZ,
                       help='Input image size')
    parser.add_argument('--patience', type=int, default=Config.YOLO_PATIENCE,
                       help='Early stopping patience')
    parser.add_argument('--cache', action='store_true', default=Config.YOLO_CACHE,
                       help='Cache images for faster training')
    parser.add_argument('--amp', action='store_true', default=Config.YOLO_AMP,
                       help='Use Automatic Mixed Precision')
    
    # Fine-tuning parameters
    parser.add_argument('--freeze_backbone', action='store_true', 
                       default=Config.YOLO_FREEZE_BACKBONE,
                       help='Freeze backbone layers')
    parser.add_argument('--freeze_until', type=int, default=Config.YOLO_FREEZE_UNTIL_LAYER,
                       help='Freeze layers up to this layer number')
    
    # Output parameters
    parser.add_argument('--project', type=str, default=str(Config.CHECKPOINT_DIR / 'yolo'),
                       help='Project directory for saving results')
    parser.add_argument('--name', type=str, default='yolo_linemod',
                       help='Name of the training run')
    parser.add_argument('--exist_ok', action='store_true',
                       help='Allow overwriting existing run')
    
    return parser.parse_args()


def main():
    args = parse_args()
    
    print("=" * 80)
    print("YOLO Training on LineMOD Dataset")
    print("=" * 80)
    print(f"\n📋 Configuration:")
    print(f"   Model: {args.model}")
    print(f"   Pretrained: {args.pretrained}")
    print(f"   Epochs: {args.epochs}")
    print(f"   Batch size: {args.batch_size}")
    print(f"   Learning rate: {args.lr}")
    print(f"   Image size: {args.imgsz}")
    print(f"   Device: {Config.DEVICE}")
    print(f"   Cache: {args.cache}")
    print(f"   AMP: {args.amp}")
    print(f"   Freeze backbone: {args.freeze_backbone}")
    if args.freeze_backbone:
        print(f"   Freeze until layer: {args.freeze_until}")
    
    # Prepare data.yaml if not provided
    if args.data_yaml is None:
        print(f"\n📊 Preparing YOLO dataset with symlinks...")
        
        # Import and run preparation
        from scripts.prepare_yolo_symlinks import prepare_yolo_dataset_symlinks, create_data_yaml
        
        output_dir = Path(args.data_dir) / 'yolo_symlinks'
        
        # Check if already prepared
        data_yaml_path = output_dir / 'data.yaml'
        if data_yaml_path.exists() and (output_dir / 'images' / 'train').exists():
            print(f"   ✅ Using existing prepared dataset: {output_dir}")
        else:
            stats = prepare_yolo_dataset_symlinks(
                dataset_root=args.data_dir,
                output_root=output_dir,
                use_symlinks=True
            )
            print(f"   ✅ Dataset prepared in {stats['time_seconds']:.1f}s")
            print(f"      Train: {stats['train']}, Val: {stats['val']}")
            
            data_yaml_path = create_data_yaml(output_dir, args.data_dir)
        
        args.data_yaml = str(data_yaml_path)
    
    print(f"\n📄 Using data.yaml: {args.data_yaml}")
    
    # Create detector
    print(f"\n🔧 Initializing yolo detector...")
    detector = YOLODetector(
        model_name=args.model,
        pretrained=args.pretrained,
        num_classes=Config.NUM_CLASSES
    )
    
    # Freeze backbone if requested
    if args.freeze_backbone:
        detector.freeze_backbone(freeze_until_layer=args.freeze_until)
    
    print(f"\n🚂 Starting training...")
    print(f"   Output: {args.project}/{args.name}")
    print(f"   Training may take time depending on hardware...")
    print(f"\n💡 Speed tips applied:")
    print(f"   • Using symlinks (no data duplication)")
    print(f"   • Image size: {args.imgsz} (smaller = faster)")
    print(f"   • Batch size: {args.batch_size}")
    print(f"   • Frozen backbone (less parameters)")
    if args.cache:
        print(f"   • Image caching enabled (faster epoch 2+)")
    if args.amp:
        print(f"   • Mixed precision training (faster on GPU)")
    
    # Train model
    results = detector.train(
        data_yaml=args.data_yaml,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch_size=args.batch_size,
        lr0=args.lr,
        project=args.project,
        name=args.name,
        patience=args.patience,
        save=True,
        exist_ok=args.exist_ok,
        verbose=True,
        cache=args.cache,
        amp=args.amp,
        workers=args.num_workers
    )
    
    print(f"\n✅ Training completed successfully!")
    print(f"\n📊 Results:")
    print(f"   Best weights: {args.project}/{args.name}/weights/best.pt")
    print(f"   Last weights: {args.project}/{args.name}/weights/last.pt")
    
    # Validate best model
    print(f"\n📈 Validating best model...")
    best_weights_path = Path(args.project) / args.name / 'weights' / 'best.pt'
    
    if best_weights_path.exists():
        # Create new detector with best weights
        best_detector = YOLODetector(
            model_name=str(best_weights_path),
            pretrained=False,
            num_classes=Config.NUM_CLASSES
        )
        
        # Run validation
        metrics = best_detector.validate(
            data_yaml=args.data_yaml,
            batch_size=args.batch_size,
            imgsz=args.imgsz
        )
        
        print(f"\n📊 Final Metrics:")
        print(f"   mAP@0.5: {metrics.box.map50:.4f}")
        print(f"   mAP@0.5:0.95: {metrics.box.map:.4f}")
        print(f"   Precision: {metrics.box.mp:.4f}")
        print(f"   Recall: {metrics.box.mr:.4f}")
    
    print(f"\n✨ All done!")
    print("=" * 80)


if __name__ == '__main__':
    main()
